/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.demo.stock.exchange;

import com.demo.stock.exchange.service.OrderService;

public class StockExchangeApplication {

    public static void main(String[] args) throws Exception {
        OrderService orderService = new OrderService();
        orderService.executeOrder(args[0]);
    }
}
